@startuml

actor User
participant ":UI" as UI
participant ":Parser" as Parser
participant ":DeleteCommand" as Command
participant ":Model" as Model
participant ":Storage" as Storage

User -> UI : "delete 1"
activate UI

UI -> Parser : parse("delete 1")
activate Parser
Parser --> UI : new DeleteCommand(1)
deactivate Parser

UI -> Command : execute()
activate Command

Command -> Model : deletePerson(1)
activate Model

Model -> Storage : saveAddressBook()
activate Storage
Storage --> Model
deactivate Storage

Model --> Command : result
deactivate Model

Command --> UI
deactivate Command

UI --> User
deactivate UI

@enduml 