@startuml
actor User

package "ClinicEase"{
component UI
component Parser
component Command
component Manager
component Object
component Storage
component Commons
}
database FileSystem

User --> UI
UI ..> Object
UI ..> Parser
UI --> Manager
UI --> Storage
Parser ..> Command
Parser ..> Object
Command --> Object
Command ..> UI
Command ..> Manager
Command ..> Storage
Manager --> Object
Manager <..> Storage
Storage ..> Object
UI --> Command
Storage --> FileSystem

@enduml