@startuml
actor User
component UI
component Parser
component Command
component Model
component Storage
database FileSystem

User --> UI
UI --> Parser
Parser ..> Command
Command ..> Model
Command --> UI

UI --> Model
UI --> Storage
Model ..> Storage
Storage --> FileSystem
@enduml 