@startuml
skinparam classAttributeIconSize 0

package "Main Component"{
class ClinicEase {
    - ManagementSystem manager
    - Ui ui
    - Storage storage

    + ClinicEase(filePath: String)
    + run(): void
    + main(args: String[]): void
}
}

ClinicEase --> UI
ClinicEase --> Storage
ClinicEase --> ManagementSystem
ClinicEase ..> Command

hide circle
@enduml