@startuml
hide footbox

participant ":ClinicEase" as ClinicEase
participant ":UI" as UI
participant ":Parser" as Parser
participant ":ViewPatientCommand" as ViewPatientCommand
participant ":ManagementSystem" as ManagementSystem
participant ":Patient" as Patient

ClinicEase -> UI : readCommand()
activate UI

UI --> ClinicEase : input
deactivate UI
ClinicEase -> Parser : parse(input)
activate Parser
Parser -> Parser : parseViewPatient(userInput)
activate Parser
Parser -> Parser : extractValue(userInput)
activate Parser
deactivate Parser
Parser --> Parser : nric :String
deactivate Parser

Parser --> ClinicEase : ViewPatientCommand

deactivate Parser

ClinicEase -> ViewPatientCommand : execute()
activate ViewPatientCommand

ViewPatientCommand -> ManagementSystem : viewPatient(nric)
activate ManagementSystem

ManagementSystem -> Patient : getPatient(nric)
activate Patient

Patient --> ManagementSystem : matchedPatient
deactivate Patient

ManagementSystem --> ViewPatientCommand
deactivate ManagementSystem

ViewPatientCommand --> UI : showPatientViewed(matchedPatient)
deactivate ViewPatientCommand
activate UI

UI --> ClinicEase : Patient details
deactivate UI

@enduml
